Add support for securityContext in controller
kubernetes-sigs/aws-ebs-csi-driver pull request #1112
Opened 2021-11-15 23:49 UTC by phantasm66

**Is this a bug fix or adding new feature?**
Bug fix for EKS kubernetes versions below `1.19`.

**What is this PR about? / Why do we need it?**
Your [compatibility matrix ](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/v1.2.1#kubernetes-version-compatibility-matrix)says that appVersion 1.2.1 of the Helm Chart supports Kubernetes versions 1.17 and above. In EKS this [does not seem to be the case](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#run-the-application-as-a-non-root-user).

We are running appVersion 1.2.1 of the `aws-ebs-csi-driver` on EKS Kubernetes `v1.18` and encountered the following error when the controller attempted to mount an EBS volume:
```
error listing AWS instances: "WebIdentityErr: failed fetching WebIdentity token: \ncaused by: WebIdentityErr: unable to read file at /var/run/secrets/eks.amazonaws.com/serviceaccount/token\ncaused by: open /var/run/secrets/eks.amazonaws.com/serviceaccount/token: permission denied"
```
This seems expected based on the AWS EKS doc I linked above, so we manually added the following to our controller Deployment live manifest and relaunched the controller pods:
```
controller:
  securityContext:
    fsGroup: 65534
```
Which immediately resulted in the EBS volume being successfully mounted:
```
  Normal  Provisioning           2m38s                  ebs.csi.aws.com_ebs-csi-controller-7b97794f89-kmhvx_c175a4ba-04a7-4508-a727-fb727d13bd58  External provisioner is provisioning volume for claim "workflow-engine/data-staging-green-zeebe-0"
  Normal  ProvisioningSucceeded  2m33s                  ebs.csi.aws.com_ebs-csi-controller-7b97794f89-kmhvx_c175a4ba-04a7-4508-a727-fb727d13bd58  Successfully provisioned volume pvc-37b7bc12-95af-4420-8f7d-a0bb2f026adc
```

**What testing is done?** 
I ran through your `make verify`, `make test` and `make test-integration` but they all failed with `ERROR: vendor check failed`, which is not a directory I touched for this PR.

2021-11-16 14:28 UTC, phantasm66 commented
Not sure why the linux foundation CLA is still showing as incomplete. I completed the individual signup last night:
```
Authorized Accounts: Linux Foundation ID "phantasm66"
GitHub https://github.com/phantasm66
```
(From the signed PDF)

2021-11-23 19:10 UTC, ayberk commented
/ok-to-test

This LGTM, but you might need to update the chart minor version. 

I'll leave the approval to @wongma7 @AndyXiangLi.

2021-11-23 20:14 UTC, phantasm66 commented
> you might need to update the chart minor version.

I saw this as a bug fix so I bumped the patch version in the `CHANGELOG.md` and `Chart.yaml`, but I'm happy to change that view if others think differently.

2021-11-23 20:45 UTC, krmichel requested changes

2021-11-23 20:45 UTC, krmichel commented on charts/aws-ebs-csi-driver/templates/controller.yaml
> +      securityContext:
`securityContext:` should be inside the `with` since it only needs to be there when the value is set.

2021-11-23 20:45 UTC, krmichel commented on charts/aws-ebs-csi-driver/Chart.yaml
> +version: 2.4.1
As far as the chart is concerned this is new functionality so you should bump the minor.

2021-11-23 22:20 UTC, krmichel approved these changes

2021-11-24 16:10 UTC, phantasm66 commented
/assign @andyxiangli

2021-12-14 11:32 UTC, phantasm66 commented
I’ll rebase this again, but can someone authorized to approve this please do so?

2021-12-14 13:38 UTC, krmichel commented
@phantasm66 when you rebase will you please fix the version in the changelog.  @ayberk or @wongma7 will one of you take a quick look at this after the rebase is done?

2021-12-14 17:29 UTC, phantasm66 commented
> when you rebase will you please fix the version in the changelog. @ayberk or @wongma7 will one of you take a quick look at this after the rebase is done?

I've rebased and bumped the Chart and appVersion's appropriately 👍

2021-12-16 05:15 UTC, ayberk commented
/lgtm
/approve

2021-12-16 05:17 UTC, merged

2021-12-16 17:17 UTC, gtxu commented
Hi @phantasm66 , there's no release v1.6.0 for now, can you bump up the chart version v2.5.1 and keeps the app version v1.5.0?

2021-12-16 18:57 UTC, phantasm66 commented
> Hi @phantasm66 , there's no release v1.6.0 for now, can you bump up the chart version v2.5.1 and keeps the app version v1.5.0?

Wasn't this already merged?

2021-12-16 20:17 UTC, phantasm66 commented
@gtxu How do you want to proceed? Do you want to revert the merge that @ayberk initiated and then I'll bump the versions down and you can re-approve/merge? I was originally told that this was adding new functionality and that the minor version should be bumped, not the patch version - which is why I went to `2.6.0` for the chart version (and it appears that the pattern for `appVersion` is 1 major less than whatever the chart version is, so `1.6.0`).

I'm happy to do whatever you need me to do, but I've received conflicting info on how y'all want contributors to set versions.

2021-12-16 20:53 UTC, krmichel commented
`2.6.0` was the correct chart version.  The appVersion isn't tied to the chart version.  I missed that the version bump didn't catch the appVersion bump in this PR.  PR #1145 has been created to fix the appVersion.

2021-12-16 20:56 UTC, gtxu commented
Hi @phantasm66 , No action needed for this now. It is fine to bump up chart version, but the `appVersion` need co-respond releasing and image publish, so the `appVersion` won't bump up with chart version usually.

2021-12-16 21:27 UTC, phantasm66 commented
> `2.6.0` was the correct chart version. The appVersion isn't tied to the chart version. I didn't catch that the last commit bumped the appVersion bump in this PR. PR #1145 has been created to fix the appVersion.

Gotcha. Sorry about that. Thanks for opening that other PR to fix the versions.