Set handle-volume-inuse-error to false
kubernetes-sigs/aws-ebs-csi-driver pull request #1280
Opened 2022-06-20 07:15 UTC by stijndehaes

If online resizing is supported this should
be set to false. Otherwise, the resizer
will watch pods and use a lot more memory.

**Is this a bug fix or adding new feature?**
This fixes: #1248

**What is this PR about? / Why do we need it?**

It set's the check to see if the volume is in use to false. This should only be turned on
when the volume supports live resizing. I believe EBS volumes support resizing when in use.

**What testing is done?** 
This setting is used in other csi implementations

2022-06-20 10:48 UTC, torredil commented
/ok-to-test

2022-06-20 11:37 UTC, torredil requested changes
Hi, thank you for your contribution! Can you please also include this change in [deploy/kubernetes/base/controller.yaml](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/b05ed2d4fc67e7986cbd026c448b349911908af4/deploy/kubernetes/base/controller.yaml#L127)? thanks.

2022-06-20 12:17 UTC, stijndehaes commented
> Hi, thank you for your contribution! Can you please also include this change in [deploy/kubernetes/base/controller.yaml](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/b05ed2d4fc67e7986cbd026c448b349911908af4/deploy/kubernetes/base/controller.yaml#L127)? thanks.

Yeah no problem! I added it to the PR

2022-06-20 13:30 UTC, torredil commented
/retest-required

2022-06-20 14:48 UTC, torredil commented
Thanks!
/lgtm
/approve
cc @gtxu @rdpsin

2022-06-20 14:49 UTC, torredil approved these changes

2022-06-20 14:51 UTC, rdpsin commented
/lgtm

2022-06-20 15:30 UTC, merged

2022-06-21 06:39 UTC, stijndehaes commented
@torredil Hey I saw master branch failing because the helm chart has the same version. Did I have to update the helm charts version in my PR? I can make a second PR to update the version if that would help :)

2022-06-21 12:28 UTC, torredil commented
@stijndehaes No worries! We are currently working on releasing `v1.7.0` and will bump up the Helm chart version as part of the release process. Thanks :)