Update workflows
kubernetes-sigs/aws-ebs-csi-driver pull request #1401
Opened 2022-09-27 20:15 UTC by torredil

**What is this PR about? / Why do we need it?**
- Add workflow to scan container images (CSI driver + sidecars) when changes are made in `'deploy/kubernetes/overlays/stable/gcr/kustomization.yaml'` and daily.
- Add workflow to scan on repo mode which helps identify potential vulnerabilities that might get introduced with new PRs.
- Remove `codeQL` workflow.

_Signed-off-by: Eddie Torres <torredil@amazon.com>_

2022-09-28 15:59 UTC, ConnorJC3 requested changes

2022-09-28 15:59 UTC, ConnorJC3 commented on .github/workflows/trivy-sidecars.yaml
> +   # Run “At minute 0 past every 24th hour.”
Remove this comment

2022-09-28 15:59 UTC, ConnorJC3 commented on .github/workflows/trivy.yaml
> +          output: 'trivy-ebs-csi-results.sarif'
Probably just call this `results.sarif` to be consistent with the other workflow?

2022-09-28 15:59 UTC, ConnorJC3 commented on .github/workflows/trivy-sidecars.yaml
> +name: Trivy Scanner - Container Images
I think this file should be renamed to `trivy-containers.yaml` or similar now that we're not just scanning the sidecars

2022-09-28 15:59 UTC, ConnorJC3 commented on .github/workflows/trivy.yaml
> +name: Trivy Scanner - EBS CSI Driver
Change name to "Trivy Scanner"

2022-09-29 15:04 UTC, torredil commented on .github/workflows/trivy.yaml
> +name: Trivy Scanner - EBS CSI Driver
Done.

2022-09-29 18:07 UTC, ConnorJC3 commented
/lgtm

2022-09-29 18:08 UTC, merged