bump csi snapshotter sidecar to 6.2.1
kubernetes-sigs/aws-ebs-csi-driver pull request #1506
Opened 2023-02-09 16:41 UTC by danbudris

**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**
EKS-D has bumped the 1.25 CSI Snapshotter to v6.2.1

**What testing is done?**

2023-02-09 17:59 UTC, torredil requested changes
Thanks for this, we should also bump up the other sidecars in this PR.

- external-provisioner -> `v3.4.0-eks-1-25-latest`
- external-attacher -> `v4.1.0-eks-1-25-latest`
- livenessprobe -> `v2.9.0-eks-1-25-latest`
- external-resizer -> `v1.7.0-eks-1-25-latest`
- node-driver-registrar -> `v2.7.0-eks-1-25-latest`

2023-02-09 17:59 UTC, torredil commented
/ok-to-test

2023-02-09 20:17 UTC, ConnorJC3 commented
Is there a particular urgency with this update? Normally we bump the sidecars as part of our monthly release.

2023-02-14 20:37 UTC, torredil commented
/close 

Addressed in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1509.

2023-02-14 20:37 UTC, closed without merging