Replace deprecated command with environment file
kubernetes-sigs/aws-ebs-csi-driver pull request #1636
Opened 2023-06-16 15:17 UTC by jongwooo

## Description

Resolve  #1635 

Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

I found the workflow files that use `set-output` command through the following command:

```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```

**AS-IS**

```yml
run: |
  echo "::set-output name=go-build::$(go env GOCACHE)"
  echo "::set-output name=go-mod::$(go env GOMODCACHE)"
```

**TO-BE**

```yml
run: |
  echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
  echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
```

2023-06-16 21:27 UTC, torredil commented
/ok-to-test

2023-06-17 00:55 UTC, ConnorJC3 commented
/retest

2023-06-20 16:11 UTC, torredil approved these changes
Thanks @jongwooo /lgtm

2023-07-03 18:53 UTC, ConnorJC3 requested changes
/hold

This PR breaks the Windows unit tests

2023-07-05 14:18 UTC, ConnorJC3 approved these changes
/remove-hold
/lgtm

Thanks! I'll leave it open a few days to make sure other maintainers have a chance to review, but this revision is good as far as I can see (you can ignore the Windows e2e test failure, it's due to a known ongoing issue).

2023-07-05 14:37 UTC, torredil commented
/approve

2023-07-05 14:38 UTC, merged