Allow additional volume mounts on node pods
kubernetes-sigs/aws-ebs-csi-driver pull request #1670
Opened 2023-07-05 13:56 UTC by AndrewSirenko

**Is this a bug fix or adding new feature?**

Feature

**What is this PR about? / Why do we need it?**

Closes #1544 

This PR adds a helm parameter that allows additional volume mounts on the node pods (and adds documentation on how to add additional volume mounts on the controller).  

This would allow users to add their own mounts to the driver via the Helm parameters `node.volumes` and `node.volumeMounts` in [this PR's values.yaml](https://github.com/AndrewSirenko/aws-ebs-csi-driver/blob/3de7fded5908a4abc731227594e76255ce4b9cdc/charts/aws-ebs-csi-driver/values.yaml#L342-L351) without needing to patch the driver. 

**What testing is done?** 

Tested on live k8s cluster. 

1. Installed the ebs-csi-driver to a test cluster with two additional volume mounts for node pods. 
<img width="730" alt="values.yaml" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/68304519/c853b046-b3fb-45e4-9b2f-26b0b5f1b52c">

2. Describing one of the node pods "kubectl describe  pod ebs-csi-node-hstbp -n kube-system" the additional two volume mounts that were requested. 
<img width="713" alt="Additional Volumes Mounted" src="https://github.com/kubernetes-sigs/aws-ebs-csi-driver/assets/68304519/8538a78e-b1e9-48ff-b4c8-16d5a2f59be6">

2023-07-05 14:06 UTC, torredil commented
/ok-to-test

2023-07-05 14:23 UTC, ConnorJC3 approved these changes
/lgtm

Given that this is the config for the EBS CSI Driver chart, "driver's node pods" and "node pods" mean the same thing - there are no other node pods that users could be confused about.

Either wording is good in my opinion, as a matter of fact "node pods" is probably slightly better as it doesn't include obvious/redundant information.

2023-07-05 14:31 UTC, torredil requested changes
Requested small changes, otherwise largely lgtm

2023-07-05 14:31 UTC, torredil commented on charts/aws-ebs-csi-driver/values.yaml
> +  volumes: [ ]
Let's do `[  ]` -> `[]` for consistency, similar to https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/280ac42f577409c1976b88cb2ebd0d9c3d161725/charts/aws-ebs-csi-driver/values.yaml#L267

Same request at 348

2023-07-05 14:31 UTC, torredil commented on charts/aws-ebs-csi-driver/values.yaml
> +  # Add additional volumes to be mounted onto the controller like:
nit: ~like~

2023-07-05 14:41 UTC, AndrewSirenko commented
> Requested small changes, otherwise largely lgtm

Fixed in latest change @torredil

2023-07-05 14:46 UTC, torredil approved these changes
Thanks for the quick turnaround, will let hanyuel take a look at this before approving /lgtm

2023-07-06 15:51 UTC, hanyuel commented
/lgtm

2023-07-06 15:54 UTC, torredil commented
/approve

2023-07-06 16:35 UTC, merged