Manage DaemonSets enablement
kubernetes-sigs/aws-ebs-csi-driver pull request #1732
Opened 2023-09-06 12:40 UTC by monicastanciu

This is a new feature needed to enable/disable the daemonset. Having different kubelet locations on clusters, there's the need to add daemonsets per each kubelet location.

2023-09-06 14:04 UTC, adriananeci commented
/ok-to-test

2023-09-06 14:18 UTC, adriananeci reviewed
/lgtm

2023-09-06 15:28 UTC, monicastanciu commented
/retest

2023-09-06 15:47 UTC, torredil commented
/retest pull-aws-ebs-csi-driver-test-helm-chart

2023-09-06 15:48 UTC, torredil commented
/test pull-aws-ebs-csi-driver-test-helm-chart

2023-09-07 08:24 UTC, monicastanciu commented
/retest

2023-09-13 13:38 UTC, torredil reviewed
Hi @monicastanciu 👋 

Looked into why the `pull-aws-ebs-csi-driver-test-helm-chart` CI job is failing and confirmed that it is not a flake -- the changes as written would break users attempting to upgrade using [reuse-values](https://helm.sh/docs/helm/helm_upgrade/) because the new parameter `enableLinux` will be `nil` by default since it did not exist in the previous chart version. Thus, the conditional `{{- if .Values.node.enableLinux }}` will evaluate to `false`, resulting in the driver `DaemonSet` not being deployed at all. 

The fix here is to modify this line:
```
{{- if .Values.node.enableLinux }}
```
to 
```
{{- if or (eq (default true .Values.node.enableLinux) true) }}
```

This will ensure that even if the parameter is not present, users can still smoothly upgrade.

----

For context, future maintainers, and contributors, here is how I went about debugging this:

1. Enable `debug` logs for CT, which output the exact commands ran.

2. CT deploys the previous chart:
```
$ helm install aws-ebs-csi-driver-8ztimfcaqj ct_previous_revision3997123812/charts/aws-ebs-csi-driver --namespace kube-system --wait --timeout 3000s
```

3. CT runs the external tests against the previous chart, which succeeds:
```
$ helm test aws-ebs-csi-driver-8ztimfcaqj --namespace kube-system --timeout 3000s
```

4. CT performs an upgrade:
```
$ helm upgrade aws-ebs-csi-driver-8ztimfcaqj charts/aws-ebs-csi-driver --namespace kube-system --reuse-values --wait --timeout 3000s
```

5. CT runs the external tests against the upgraded chart, which fails:
```
$ Summarizing 11 Failures:
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (delayed binding)] topology [It] should provision a volume and schedule a pod with AllowedTopologies
  test/e2e/storage/testsuites/topology.go:172
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (default fs)] volumes [It] should store data
  test/e2e/framework/volume/fixtures.go:584
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand [It] should resize volume when PVC is edited while pod is using it
  test/e2e/storage/testsuites/volume_expand.go:261
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (ext4)] volumes [It] should store data
  test/e2e/framework/volume/fixtures.go:584
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand [It] should resize volume when PVC is edited while pod is using it
  test/e2e/storage/testsuites/volume_expand.go:261
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand [It] Verify if offline PVC expansion works
  test/e2e/storage/testsuites/volume_expand.go:191
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (xfs)][Slow] volumes [It] should store data
  test/e2e/framework/volume/fixtures.go:584
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand [It] Verify if offline PVC expansion works
  test/e2e/storage/testsuites/volume_expand.go:191
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (default fs)] volumeIO [It] should write files of various sizes, verify size, validate content [Slow]
  test/e2e/storage/testsuites/volume_io.go:158
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (immediate binding)] topology [It] should provision a volume and schedule a pod with AllowedTopologies
  test/e2e/storage/testsuites/topology.go:172
  [FAIL] External Storage [Driver: ebs.csi.aws.com] [Testpattern: Dynamic PV (block volmode)] volumes [It] should store data
  test/e2e/framework/volume/fixtures.go:584

Ran 11 of 7486 Specs in 423.216 seconds
FAIL! -- 0 Passed | 11 Failed | 0 Pending | 7475 Skipped
```
* while the tests where running, pod logs were streamed to get the output above `kubectl logs -f -n kube-system ebs-csi-driver-test -n kube-system`. After confirming that the external tests failed, I looked at the controller pod logs and saw `"error generating accessibility requirements: no topology key found on CSINode"`, which was the clue that helped me understand what was going on. I then ran `$ kubectl get daemonset --all-namespaces` and verified that the `DaemonSet` was not deployed:

```
$ kubectl get daemonset --all-namespaces                                                                                                                                                                                                                                                                     
NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   aws-cloud-controller-manager   1         1         1       1            1           <none>          4h7m
kube-system   kops-controller                1         1         1       1            1           <none>          4h7m

```

2023-09-13 13:40 UTC, torredil requested changes
Appreciate your contribution 👍

2023-09-13 13:40 UTC, torredil commented on charts/aws-ebs-csi-driver/templates/_node.tpl
> +{{- if .Values.node.enableLinux }}
Change to `{{- if or (eq (default true .Values.node.enableLinux) true) }}`.

2023-09-13 13:40 UTC, torredil commented on charts/aws-ebs-csi-driver/CHANGELOG.md
> +
Thanks for adding this : ) 

We typically have a maintainer who performs releases make these changes so let's remove it.

2023-09-13 13:40 UTC, torredil commented on charts/aws-ebs-csi-driver/Chart.yaml
> +version: 2.22.1
Thanks for adding this : ) 

We typically have a maintainer who performs releases make these changes so let's remove it.

2023-09-13 15:24 UTC, torredil approved these changes
@monicastanciu Thanks for the quick turnaround! this looks great.

Just one last request: let's squash the commits https://www.kubernetes.dev/docs/guide/pull-requests/#squashing and add a comment similar to https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/9cec97eaf9839051d95d97b970c5690e747378fb/charts/aws-ebs-csi-driver/values.yaml#L299 so that users know exactly what tuning this parameter does.

Thank you Monica.

cc: @ConnorJC3 @AndrewSirenko for review.

2023-09-14 15:37 UTC, ConnorJC3 commented
/lgtm

2023-09-14 17:40 UTC, ConnorJC3 commented
/lgtm

2023-09-14 17:42 UTC, torredil commented
/approve

2023-09-14 18:29 UTC, torredil commented
/retest

2023-09-14 18:52 UTC, merged