Increase default QPS and worker threads of sidecars
kubernetes-sigs/aws-ebs-csi-driver pull request #1834
Opened 2023-11-09 17:27 UTC by ConnorJC3

WIP

**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**

**What testing is done?**

2023-11-09 17:40 UTC, AndrewSirenko approved these changes

2023-11-09 17:46 UTC, torredil requested changes
```
$ kubectl get pods -A | grep "ebs"

kube-system   ebs-csi-controller-68bbbf668b-vbzd2    5/6     CrashLoopBackOff   4 (59s ago)   2m27s
kube-system   ebs-csi-controller-68bbbf668b-wr88p    5/6     CrashLoopBackOff   4 (63s ago)   2m27s
kube-system   ebs-csi-node-2jr6c                     3/3     Running            0             2m27s
kube-system   ebs-csi-node-kbzcm                     3/3     Running            0             2m27s
```

```
$ kubectl logs ebs-csi-controller-68bbbf668b-vbzd2 -n kube-system -c csi-resizer

flag provided but not defined: -worker-threads
```

resizer uses `workers`: https://github.com/kubernetes-csi/external-resizer

2023-11-09 17:47 UTC, torredil commented
Small change otherwise lgtm

2023-11-09 18:35 UTC, torredil approved these changes
Thanks!

/lgtm
/approve

2023-11-09 19:15 UTC, merged

2024-05-22 15:04 UTC, AbeOwlu commented
@ConnorJC3 , quick inquiry on the trajectory of the ebs controller regarding client side qps and burst config;
- the upstream idea is to eventually let the server P&F decide on load handling and rate limiting response. Is this on the path for ebs csi?

2024-05-22 16:55 UTC, ConnorJC3 commented
@AbeOwlu we take the upstream sidecars essentially as-is, so if this change is made there it will automatically be integrated in the EBS CSI Driver.