Make govulncheck optional for merge
kubernetes-sigs/aws-ebs-csi-driver pull request #2132
Opened 2024-08-30 16:30 UTC by AndrewSirenko

**Is this a bug fix or adding new feature?**

N/A

**What is this PR about? / Why do we need it?**

This makes the govulncheck CI Job optional for merges. This solves two issues:
- New vulnerability blocks the merge of a new contributor, requiring a rebase. This is not a great contributor experience and has led to delays due to PR churn.
- A false positive in the vulnerability database has blocked our release twice in the past year. There is no way to exclude vulnerability reports with the current govulncheck, though there is a hand-crafted example of this [here](https://github.com/tianon/gosu/blob/master/govulncheck-with-excludes.sh).

The risk here is that now merging a change that fails this CI is possible. However, that threat is handled by only having a limited amount of approvers for our repository, and an explicit release runbook step of no active vulnerabilities during out dependency upgrade PR. 

**What testing is done?** 

CI,

/hold

Will test with fake commit including a dependency with known vulnerability in PR

2024-09-04 14:10 UTC, ConnorJC3 requested changes
From what I can tell reading the GitHub docs, this will make it impossible for the job to fail at all, which means that we will not get the feedback unless someone goes out of their way to read the job results.

It's possible that I am wrong, but please test this in a personal fork and link example PRs here so that we can see what the result looks like before merging.

2024-09-04 14:23 UTC, AndrewSirenko commented
Thank you for your concern @ConnorJC3, but please hold off on review until it is no longer marked WIP because I have yet to do the testing that I described in PR comment.

What I saw from the docs and relevant stack overflow posts was that the job will fail with a red X, the failure will not block other CI actions for the PR. So there will be a failure shown without blocking merge, but this must be validated.

2024-09-10 23:36 UTC, ConnorJC3 commented
My suggestion would be to run it only on the release branch. If we make it optional on Prow, we are going to eventually accidentally merge a release with a known CVE.

There's no circumstance where we would want to intentionally merge a release PR containing known vulnerabilities, so the only potential downside of this solution is false positives. False positives are very rare (I think we've had one over the past year?) and the only reason we're talking about them is recency bias. Additionally, it's trivial to disable the job if that ever happens during a release.

2024-09-11 23:55 UTC, AndrewSirenko commented
/unhold

2024-09-12 13:29 UTC, ConnorJC3 approved these changes
/lgtm

2024-09-12 13:56 UTC, torredil approved these changes
/approve

2024-09-12 13:57 UTC, merged