Add v1 Karpenter disrupted taint to pre-stop hook
kubernetes-sigs/aws-ebs-csi-driver pull request #2166
Opened 2024-10-03 14:13 UTC by AndrewSirenko

**Is this a bug fix or adding new feature?**
Bug fix

**What is this PR about? / Why do we need it?**
Fixes #2158 

Our pre-stop hook attempts to keep the EBS CSI Driver node plugin alive while node is being drained so that it can Unstage/Unpublish all volumes and report that to Kubelet before node termination. Karpenter v1 changed their disruption taint, so we need to update our pre-stop hook to check for it. 

We also remove the dependency on Karpenter because we are compatible with multiple versions of it, and switch to just checking taint key instead of taint key and effect in case these auto-scalars switch to a `NoExecute` effect.

**What testing is done?** 
New unit tests. 

TODO test with karpenter v1.

2024-10-03 16:30 UTC, AndrewSirenko commented
/retest

windows flake for volume expansion

2024-10-04 17:24 UTC, torredil approved these changes

2024-10-04 17:37 UTC, ElijahQuinones approved these changes

2024-10-07 17:24 UTC, ConnorJC3 requested changes
One minor change otherwise lgtm

2024-10-07 17:56 UTC, AndrewSirenko commented on cmd/hooks/prestop.go
> +var drainTaints = map[string]bool{
I actually saw this go hack online a couple times but I personally thought it is less readable which is why I decided against it. 

I don't think saving a few bytes of RAM on pre-stop hook is not worth the readability hit for such a small map. (E.g. map of strings-> booleans is self documenting versus map of string -> empty structs might not be)

But if the team would rather have it changed I'm open to it. @ElijahQuinones @torredil.

2024-10-07 18:04 UTC, ElijahQuinones commented on cmd/hooks/prestop.go
> +var drainTaints = map[string]bool{
I don't have a hard stance ether way but maybe we can go in the middle Connors change with a comment to make it more readable ?

2024-10-07 18:20 UTC, ConnorJC3 commented on cmd/hooks/prestop.go
> +var drainTaints = map[string]bool{
It's _more_ readable - the existing code makes you wonder what the `true` means, and you have to read elsewhere to find out it's entirely arbitrary (`false` would do the same thing).

Using `struct{}` leaves no room for thinking switching to `false` would somehow change the behavior or remove the value from the considered taints. It also makes this easy to perform error a syntax error: `if isDrainTaint = drainTaints[someValue]; isDrainTaint {`, which is valid under the bool setup.

Finally, and probably most importantly: `struct{}` is how we already do this pattern everywhere else in our code:
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/eaabf29cf318e0135ed78659c3cf68e3efd71af5/pkg/driver/constants.go#L191-L227
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/eaabf29cf318e0135ed78659c3cf68e3efd71af5/pkg/cloud/interface.go#L40
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/eaabf29cf318e0135ed78659c3cf68e3efd71af5/pkg/cloud/cloud.go#L184-L193
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/eaabf29cf318e0135ed78659c3cf68e3efd71af5/pkg/cloud/volume_limits.go#L55-L71

2024-10-07 18:30 UTC, ConnorJC3 commented on cmd/hooks/prestop.go
> +var drainTaints = map[string]bool{
I have no idea what that reddit post is, have never read it, and don't think we should be making decisions based on random reddit comments one way or the other.

>  For bool values you can do a simple m[k] which is less to type and is easier to understand.

The problem with this is that it makes `ok := map[key]` and `_, ok := map[key]` both valid checks that are arguably correct but mean different things - the bool stores redundant information and it isn't clear to the reader what it represents or what a `false` value would mean - making the code less readable.

2024-10-07 18:34 UTC, AndrewSirenko commented on cmd/hooks/prestop.go
> +var drainTaints = map[string]bool{
Thank you for your feedback, I have changed the PR accordingly

2024-10-07 18:35 UTC, ConnorJC3 approved these changes
/lgtm

2024-10-07 18:36 UTC, torredil commented
/approve

2024-10-07 18:49 UTC, ElijahQuinones commented
/retest

2024-10-07 18:49 UTC, AndrewSirenko commented
@ElijahQuinones  Not a flake, need to reformat the module import

2024-10-07 18:51 UTC, AndrewSirenko commented
/unhold

2024-10-07 18:53 UTC, ConnorJC3 commented
/lgtm

2024-10-07 19:34 UTC, merged