[helm] add tag options and update csi-provisioner
kubernetes-sigs/aws-ebs-csi-driver pull request #577
Opened 2020-10-03 08:04 UTC by kcking

**Is this a bug fix or adding new feature?**
Feature
**What is this PR about? / Why do we need it?**
Add options to create EBS volume tags that the in-tree plugin creates
**What testing is done?** 
Tested within our EKS 1.17 cluster, confirmed that new volumes have correct names/tags.

2020-10-03 08:19 UTC, kcking commented
Check CLA again

2020-10-08 06:13 UTC, leakingtapan reviewed
/ok-to-test
Could you update the chat version as well?

2020-10-08 06:40 UTC, kcking commented
Sure thing, just bumped it to `0.6.1`

2020-10-08 18:31 UTC, jwesolowski-rms commented
@kcking this looks great. @leakingtapan Is it possible to get this merged in assuming all looks fine to you?

2020-10-08 18:38 UTC, jwesolowski-rms approved these changes

2020-10-08 18:44 UTC, jwesolowski-rms requested changes
Whoops. Just saw one thing. @kcking for consistency, I'm thinking adding the new `k8sTagClusterId` and `extraCreateMetadata` values to the values.yaml with a default and comment would be helpful. This would be similar to what we have for [enableVolumeScheduling](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/aws-ebs-csi-driver/values.yaml#L38-L39).

2020-10-08 18:46 UTC, kcking commented
Sure thing. I'm thinking a default of `kubernetes` for `k8sTagClusterId` as I think the in-tree plugin creates volumes with a prefix of `kubernetes`. Alternatively we could not specify by default but leave it defined in a comment

Then should we default `extraCreateMetadata` to true or false?

2020-10-08 18:58 UTC, jwesolowski-rms commented
I think I would lean towards mimicking the defaults in the controller and csi-provisioner itself:
-  `k8sTagClusterId` defaults to `""` ([link](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/44ec7de2c953b52c9fd39e85ca2183aab6465d32/cmd/options/controller_options.go#L37))
- `extraCreateMetadata` defaults to `false` ([link](https://github.com/kubernetes-csi/external-provisioner/blob/8b0707649212d770624008edbd127f312121aff9/cmd/csi-provisioner/csi-provisioner.go#L72))

2020-10-08 19:09 UTC, kcking commented
@jwesolowski-rms thank you for the links! Just added them

2020-10-08 19:11 UTC, jwesolowski-rms approved these changes
@kcking thanks for the modifications! Looks perfect.

2020-10-08 19:37 UTC, jwesolowski-rms commented
/retest

2020-10-14 20:23 UTC, jwesolowski-rms commented
@leakingtapan any update on this?

2020-10-14 23:56 UTC, leakingtapan commented
/lgtm
/approve

2020-10-15 14:49 UTC, jwesolowski-rms commented
/retest

2020-10-15 15:12 UTC, merged